version: '3.9'

services:

  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env  
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: fastApiTddDb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

name: fastapi-development
      
